### ISSUE TITLE
Option to temporarily disable redirect through extension icon

### ISSUE THREAD

**Issue by austinhuang0131** [raikasdev/mastodon4-redirect#1]
Since there exists no guarantee (and it's often not the case) that an instance has the post that the user wants to interact with, they should be able to select the post from the remote profile, or the reply from the remote post, and send it to their own instance. Hence they might want to temporarily not redirect profiles.

**Comment by raikasdev** [comment]
Implemented as of https://github.com/raikasdev/mastodon4-redirect/commit/b59d5662f726235b0ed5e76a228d88b954a9fb5f
