### ISSUE TITLE
Can't install from addons.mozilla.org after clicking the badge in readme

### ISSUE THREAD

**Issue by marcin-kozinski** [raikasdev/mastodon4-redirect#2]
Hey,

When I click the "Get the Add-on" badge in readme, addons.mozilla.org opens but I can't install the add-on. I see a red warning that says "This add-on is not available on your platform." and lower a yellow warning that says "This listing is not intended for this platform. [Browse add-ons for Firefox on desktop](https://addons.mozilla.org/en-US/firefox/addon/mastodon4-redirect/)." I think this is because of linking to a wrong URL, I don't think it should include `/android/`.

<img width="985" alt="Screenshot 2022-11-17 at 16 37 31" src="https://user-images.githubusercontent.com/2088582/202490389-1ace390e-b823-4b47-9a4d-f8679e441fbc.png">

I can send a PR to fix the link in README, just wanted to raise first in case I don't understand something and `/android` is expected in the URL.

I'm on Firefox Desktop 107.0 (64-bit) on macos. I also tried opening with Firefox on Android, but it also doesn't want to install the extension.

**Comment by raikasdev** [comment]
Fixed this, thank you!
