### ISSUE TITLE
Optionally ignore redirect from main feeds

### ISSUE THREAD

**Issue by rollecode** [raikasdev/mastodon4-redirect#3]
What I'd like to do is to browse content from other instances, like [mastodon.social/explore](https://mastodon.social/explore), then click myself to posts and users so that those only would redirect back to my own instance.

Right now all the urls redirect back to my own so I lose the advantage of seeing different content this way.

Could you add option to disable /explore /public and /public/local redirect?

**Comment by rollecode** [comment]
Oh and also it would be nice to be able to ignore  [/following](https://mastodo.fi/@mirppu/following) so that you could just click yourself to profiles.

**Comment by raikasdev** [comment]
Hey, sorry for the bit late reply! Will implement this in the coming days.
